# Generated by Django 4.1.7 on 2023-04-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='area_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='area_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='area_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='area_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='area_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rooms_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rooms_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rooms_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rooms_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rooms_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='square_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='square_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='square_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='square_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='square_tr',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Максимум 20 символов', verbose_name='Цена'),
        ),
    ]
