# Generated by Django 4.1.7 on 2023-04-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ilan', '0002_remove_product_area_ar_remove_product_area_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=300, verbose_name='Э-Почта Клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('customer_name', models.CharField(max_length=250, verbose_name='Имя Клиента')),
                ('message', models.TextField(max_length=2000, verbose_name='Сообщение Клиента')),
                ('checked', models.BooleanField(default=True, verbose_name='Проверено или НЕТ')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ilan.product', verbose_name='ID объекта')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звонки',
                'db_table': 'callback',
                'ordering': ['checked'],
            },
        ),
    ]
