# Generated by Django 4.1.7 on 2023-04-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitle',
            options={'verbose_name': 'Подзаголовок', 'verbose_name_plural': 'Подзаголовки'},
        ),
    ]
